name: Pull Request Project Automation

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
    with:
      username: ${{ github.event.pull_request.user.login }}

  WorkingBoardReview:
    needs: community_check
    runs-on: ubuntu-latest
    steps:
      - name: 'Move team PRs to Review column'
        if: github.event.pull_request.draft == false && needs.community_check.outputs.maintainer == 'true'
        env:
          DESTINATION_COLUMN_ID: 'MDEzOlByb2plY3RDb2x1bW4xMTUxMzYzOA=='
          GH_TOKEN: ${{ secrets.ORGSCOPED_GITHUB_TOKEN }}
        run: |
          PROJCOLUMNS=$(gh api graphql -f query='
              query {
                repository(name: "${{ github.event.repository.name }}", owner: "${{ github.repository_owner }}") {
                  pullRequest(number: ${{ github.event.pull_request.number }}) {
                  projectCards {
                    nodes {
                      column {
                        name
                        id
                      }
                    }
                  }
                }
              }
            }')
          INPROJECT=$(echo $PROJCOLUMNS | jq '.data.repository.pullRequest.projectCards.nodes[].column | select(.id=="${{ env.DESTINATION_COLUMN_ID }}")')
          if [ -z "$INPROJECT" ];
          then
            gh api graphql -f query='mutation {
              addProjectCard(input: {projectColumnId: "${{ env.DESTINATION_COLUMN_ID }}", contentId: "${{ github.event.pull_request.node_id }}"}) {
                clientMutationId
              }
            }'
          fi
